# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'history.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HisWindow(object):
    def setupUi(self, HisWindow):
        HisWindow.setObjectName("HisWindow")
        HisWindow.resize(921, 884)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(HisWindow.sizePolicy().hasHeightForWidth())
        HisWindow.setSizePolicy(sizePolicy)
        HisWindow.setMinimumSize(QtCore.QSize(921, 884))
        HisWindow.setMaximumSize(QtCore.QSize(921, 884))
        self.centralwidget = QtWidgets.QWidget(HisWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 520, 351, 291))
        self.groupBox.setObjectName("groupBox")
        self.Imglabel = QtWidgets.QLabel(self.groupBox)
        self.Imglabel.setGeometry(QtCore.QRect(20, 30, 311, 241))
        self.Imglabel.setText("")
        self.Imglabel.setObjectName("Imglabel")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(450, 660, 431, 161))
        self.groupBox_2.setObjectName("groupBox_2")
        self.Infolabel = QtWidgets.QLabel(self.groupBox_2)
        self.Infolabel.setGeometry(QtCore.QRect(40, 30, 371, 71))
        self.Infolabel.setText("")
        self.Infolabel.setObjectName("Infolabel")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, 30, 221, 51))
        self.label.setObjectName("label")
        self.head = QtWidgets.QLabel(self.centralwidget)
        self.head.setGeometry(QtCore.QRect(750, 20, 71, 61))
        self.head.setText("")
        self.head.setPixmap(QtGui.QPixmap("../images/doctor.png"))
        self.head.setObjectName("head")
        self.doctor_name = QtWidgets.QLabel(self.centralwidget)
        self.doctor_name.setGeometry(QtCore.QRect(370, 30, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.doctor_name.setFont(font)
        self.doctor_name.setMouseTracking(False)
        self.doctor_name.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doctor_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doctor_name.setObjectName("doctor_name")
        self.back = QtWidgets.QLabel(self.centralwidget)
        self.back.setGeometry(QtCore.QRect(840, 30, 71, 41))
        self.back.setText("")
        self.back.setPixmap(QtGui.QPixmap("../images/return.png"))
        self.back.setObjectName("back")
        self.table1 = QtWidgets.QTableWidget(self.centralwidget)
        self.table1.setGeometry(QtCore.QRect(30, 80, 531, 381))
        self.table1.setStyleSheet("QTableWidget::item::selected\n"
"{\n"
"    background:gray;\n"
"     border-bottom:1px solid #EEF1F7;\n"
"}")
        self.table1.setObjectName("table1")
        self.table1.setColumnCount(4)
        self.table1.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table1.setHorizontalHeaderItem(3, item)
        self.table1.horizontalHeader().setDefaultSectionSize(130)
        self.table1.verticalHeader().setVisible(False)
        self.table1.verticalHeader().setDefaultSectionSize(45)
        self.advice = QtWidgets.QTextEdit(self.centralwidget)
        self.advice.setGeometry(QtCore.QRect(600, 190, 301, 261))
        self.advice.setObjectName("advice")
        self.give_advice = QtWidgets.QPushButton(self.centralwidget)
        self.give_advice.setGeometry(QtCore.QRect(820, 490, 93, 28))
        self.give_advice.setStyleSheet("QPushButton{\n"
"    font: 11pt \"微软雅黑\";\n"
"    color: #2f3640;\n"
"    background-color: #f5f6fa;\n"
"    border-color: #2f3640;\n"
"    border-radius: 15px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton::hover{    \n"
"    color: #FFFFFF;\n"
"    background-color: #718093;\n"
"    border-color: #2f3640;\n"
"}\n"
"\n"
"QPushButton::pressed,QPushButton::checked{\n"
"    color: #FFFFFF;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #273c75, stop:1 #487eb0);\n"
"}\n"
"QPushButton::disabled{\n"
"    color: #FFFFFF;\n"
"    background-color: #dcdde1;\n"
"    border-color: #dcdde1;\n"
"}\n"
"\n"
"")
        self.give_advice.setObjectName("give_advice")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(620, 130, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.search_content = QtWidgets.QLineEdit(self.centralwidget)
        self.search_content.setGeometry(QtCore.QRect(390, 470, 171, 41))
        self.search_content.setAlignment(QtCore.Qt.AlignCenter)
        self.search_content.setObjectName("search_content")
        self.search = QtWidgets.QLabel(self.centralwidget)
        self.search.setGeometry(QtCore.QRect(320, 470, 61, 51))
        self.search.setText("")
        self.search.setPixmap(QtGui.QPixmap("../../resource/find.png"))
        self.search.setObjectName("search")
        HisWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HisWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 921, 26))
        self.menubar.setObjectName("menubar")
        HisWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HisWindow)
        self.statusbar.setObjectName("statusbar")
        HisWindow.setStatusBar(self.statusbar)
        self.logout = QtWidgets.QAction(HisWindow)
        self.logout.setObjectName("logout")

        self.retranslateUi(HisWindow)
        QtCore.QMetaObject.connectSlotsByName(HisWindow)

    def retranslateUi(self, HisWindow):
        _translate = QtCore.QCoreApplication.translate
        HisWindow.setWindowTitle(_translate("HisWindow", "Auxiliar Tools"))
        self.groupBox.setTitle(_translate("HisWindow", "Iamge display"))
        self.groupBox_2.setTitle(_translate("HisWindow", "Result display"))
        self.label.setText(_translate("HisWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; font-style:italic; color:#00557f;\">History</span></p><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; font-style:italic; color:#00557f;\"><br/></span></p></body></html>"))
        self.doctor_name.setText(_translate("HisWindow", "Doc name"))
        item = self.table1.horizontalHeaderItem(0)
        item.setText(_translate("HisWindow", "patient_id"))
        item = self.table1.horizontalHeaderItem(1)
        item.setText(_translate("HisWindow", "patient_name"))
        item = self.table1.horizontalHeaderItem(2)
        item.setText(_translate("HisWindow", "patient_age"))
        item = self.table1.horizontalHeaderItem(3)
        item.setText(_translate("HisWindow", "date"))
        self.give_advice.setText(_translate("HisWindow", "submit"))
        self.label_2.setText(_translate("HisWindow", "Advice"))
        self.search_content.setPlaceholderText(_translate("HisWindow", "Enter the name"))
        self.logout.setText(_translate("HisWindow", "退出"))
