# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(526, 324)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(526, 324))
        Form.setMaximumSize(QtCore.QSize(526, 324))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../picture/wel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 40, 71, 61))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../images/welcome.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(120, 30, 381, 91))
        self.label_2.setObjectName("label_2")
        self.edit_username = QtWidgets.QLineEdit(Form)
        self.edit_username.setGeometry(QtCore.QRect(140, 130, 251, 31))
        self.edit_username.setObjectName("edit_username")
        self.edit_password = QtWidgets.QLineEdit(Form)
        self.edit_password.setGeometry(QtCore.QRect(140, 170, 251, 31))
        self.edit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.edit_password.setObjectName("edit_password")
        self.btn_login = QtWidgets.QPushButton(Form)
        self.btn_login.setGeometry(QtCore.QRect(140, 220, 251, 31))
        self.btn_login.setObjectName("btn_login")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Login"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#8269ff;\">liver steatosis diagnostic tools</span></p></body></html>"))
        self.edit_username.setPlaceholderText(_translate("Form", "username"))
        self.edit_password.setPlaceholderText(_translate("Form", "password"))
        self.btn_login.setText(_translate("Form", "Login"))
