# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(921, 884)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(921, 884))
        MainWindow.setMaximumSize(QtCore.QSize(921, 884))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(340, 70, 551, 461))
        self.groupBox.setObjectName("groupBox")
        self.Imglabel = QtWidgets.QLabel(self.groupBox)
        self.Imglabel.setGeometry(QtCore.QRect(20, 30, 511, 411))
        self.Imglabel.setText("")
        self.Imglabel.setObjectName("Imglabel")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(340, 540, 531, 101))
        self.groupBox_2.setObjectName("groupBox_2")
        self.Infolabel = QtWidgets.QLabel(self.groupBox_2)
        self.Infolabel.setGeometry(QtCore.QRect(40, 30, 371, 71))
        self.Infolabel.setText("")
        self.Infolabel.setObjectName("Infolabel")
        self.fileBtn = QtWidgets.QPushButton(self.centralwidget)
        self.fileBtn.setGeometry(QtCore.QRect(20, 590, 271, 61))
        self.fileBtn.setStyleSheet("QPushButton{\n"
"    font: 11pt \"微软雅黑\";\n"
"    color: #2f3640;\n"
"    background-color: #f5f6fa;\n"
"    border-color: #2f3640;\n"
"    border-radius: 15px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    padding: 5px;\n"
"}rgb(211, 234, 255)")
        self.fileBtn.setObjectName("fileBtn")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(30, 70, 261, 481))
        self.listWidget.setObjectName("listWidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 351, 51))
        self.label.setObjectName("label")
        self.head = QtWidgets.QLabel(self.centralwidget)
        self.head.setGeometry(QtCore.QRect(740, 10, 71, 61))
        self.head.setText("")
        self.head.setPixmap(QtGui.QPixmap("../images/doctor.png"))
        self.head.setObjectName("head")
        self.doctor_name = QtWidgets.QLabel(self.centralwidget)
        self.doctor_name.setGeometry(QtCore.QRect(370, 20, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.doctor_name.setFont(font)
        self.doctor_name.setMouseTracking(False)
        self.doctor_name.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.doctor_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doctor_name.setObjectName("doctor_name")
        self.patient_name = QtWidgets.QLineEdit(self.centralwidget)
        self.patient_name.setGeometry(QtCore.QRect(100, 690, 111, 31))
        self.patient_name.setObjectName("patient_name")
        self.patient_age = QtWidgets.QLineEdit(self.centralwidget)
        self.patient_age.setGeometry(QtCore.QRect(100, 740, 111, 31))
        self.patient_age.setObjectName("patient_age")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 700, 41, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 750, 41, 16))
        self.label_3.setObjectName("label_3")
        self.btn_advice = QtWidgets.QPushButton(self.centralwidget)
        self.btn_advice.setGeometry(QtCore.QRect(780, 800, 93, 28))
        self.btn_advice.setStyleSheet("QPushButton{\n"
"    font: 11pt \"微软雅黑\";\n"
"    color: #2f3640;\n"
"    background-color: #f5f6fa;\n"
"    border-color: #2f3640;\n"
"    border-radius: 15px;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton::hover{    \n"
"    color: #FFFFFF;\n"
"    background-color: #718093;\n"
"    border-color: #2f3640;\n"
"}\n"
"\n"
"QPushButton::pressed,QPushButton::checked{\n"
"    color: #FFFFFF;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #273c75, stop:1 #487eb0);\n"
"}\n"
"QPushButton::disabled{\n"
"    color: #FFFFFF;\n"
"    background-color: #dcdde1;\n"
"    border-color: #dcdde1;\n"
"}\n"
"\n"
"")
        self.btn_advice.setObjectName("btn_advice")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(310, 645, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.advice = QtWidgets.QTextEdit(self.centralwidget)
        self.advice.setGeometry(QtCore.QRect(310, 690, 571, 91))
        self.advice.setObjectName("advice")
        self.history = QtWidgets.QLabel(self.centralwidget)
        self.history.setGeometry(QtCore.QRect(840, 20, 71, 41))
        self.history.setText("")
        self.history.setPixmap(QtGui.QPixmap("../images/history.png"))
        self.history.setObjectName("history")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 921, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.logout = QtWidgets.QAction(MainWindow)
        self.logout.setObjectName("logout")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Auxiliar Tools"))
        self.groupBox.setTitle(_translate("MainWindow", "Image display"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Result display"))
        self.fileBtn.setText(_translate("MainWindow", "upload"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; font-style:italic; color:#9086ff;\">liver steatosis diagnostic tool</span></p></body></html>"))
        self.doctor_name.setText(_translate("MainWindow", "Doc name"))
        self.label_2.setText(_translate("MainWindow", "Name"))
        self.label_3.setText(_translate("MainWindow", "Age"))
        self.btn_advice.setText(_translate("MainWindow", "submit"))
        self.label_4.setText(_translate("MainWindow", "Diagnostic suggestion\n"
""))
        self.logout.setText(_translate("MainWindow", "退出"))
